In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("instagram_reach.csv")
df

,Unnamed: 0,S.No,USERNAME,Caption,Followers,Hashtags,Time since posted,Likes
0,0,1,mikequindazzi,Who are #DataScientist and what do they do? >>...,1600,#MachineLearning #AI #DataAnalytics #DataScien...,11 hours,139
1,1,2,drgorillapaints,We all know where it’s going. We just have to ...,880,#deck .#mac #macintosh#sayhello #apple #steve...,2 hours,23
2,2,3,aitrading_official,Alexander Barinov: 4 years as CFO in multinati...,255,#whoiswho #aitrading #ai #aitradingteam#instat...,2 hours,25
3,3,4,opensourcedworkplace,sfad,340,#iot #cre#workplace #CDO #bigdata #technology#...,3 hours,49
4,4,5,crea.vision,Ever missed a call while your phone was chargi...,304,#instamachinelearning #instabigdata#instamarke...,3 hours,30
...,...,...,...,...,...,...,...,...
95,8,19,michaelgarza__,"328 S. Wetherly Drive, Beverly Hills, CA 90212...",614,#beverlyhills #realestate#losangelesrealestate...,3 hours,31
96,9,21,dvlp_search,Credit @tristankappel To find more dvlp follow...,450,#workspace #work #developer#development #devel...,3 hours,42
97,10,22,ecom.space,We are coming up with the Best 21 Books that w...,182,#books #book #motivation #inspiration #life#bo...,3 hours,10
98,11,24,lb3enterprises,We’re only paid to move dirt once. It’s not ju...,2039,#heavyequipment #underconstruction#dozer #real...,3 hours,222
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109

In [8]:
def remove_special_chars(string):
    return ''.join(letter for letter in string if letter.isalnum() or letter == " ")

In [24]:
# df["Caption"].str.split(" ")
df["Caption"] =df["Caption"].fillna("")
df["Caption_splited"] = df["Caption"].apply(remove_special_chars).str.split(" ")

In [25]:
# df["Hashtags"].str.split("#")
df["Hashtags"] =df["Hashtags"].fillna("")
df["Hashtags_splited"] = df["Hashtags"].apply(remove_special_chars).str.split(" ")

In [26]:
df

,Unnamed: 0,S.No,USERNAME,Caption,Followers,Hashtags,Time since posted,Likes,Hashtags_splited,Caption_splited
0,0,1,mikequindazzi,Who are #DataScientist and what do they do? >>...,1600,#MachineLearning #AI #DataAnalytics #DataScien...,11 hours,139,"[MachineLearning, AI, DataAnalytics, DataScien...","[Who, are, DataScientist, and, what, do, they,..."
1,1,2,drgorillapaints,We all know where it’s going. We just have to ...,880,#deck .#mac #macintosh#sayhello #apple #steve...,2 hours,23,[deckmacmacintoshsayhelloapplestevejobsaievolu...,"[We, all, know, where, its, going, We, just, h..."
2,2,3,aitrading_official,Alexander Barinov: 4 years as CFO in multinati...,255,#whoiswho #aitrading #ai #aitradingteam#instat...,2 hours,25,[whoiswhoaitradingaiaitradingteaminstateaminst...,"[Alexander, Barinov, 4, years, as, CFO, in, mu..."
3,3,4,opensourcedworkplace,sfad,340,#iot #cre#workplace #CDO #bigdata #technology#...,3 hours,49,[iotcreworkplaceCDObigdatatechnologytechworkco...,[sfad]
4,4,5,crea.vision,Ever missed a call while your phone was chargi...,304,#instamachinelearning #instabigdata#instamarke...,3 hours,30,[instamachinelearninginstabigdatainstamarketin...,"[Ever, missed, a, call, while, your, phone, wa..."
...,...,...,...,...,...,...,...,...,...,...
95,8,19,michaelgarza__,"328 S. Wetherly Drive, Beverly Hills, CA 90212...",614,#beverlyhills #realestate#losangelesrealestate...,3 hours,31,[beverlyhillsrealestatelosangelesrealestategcm...,"[328, S, Wetherly, Drive, Beverly, Hills, CA, ..."
96,9,21,dvlp_search,Credit @tristankappel To find more dvlp follow...,450,#workspace #work #developer#development #devel...,3 hours,42,[workspaceworkdeveloperdevelopmentdeveloperlif...,"[CredittristankappelTo, find, more, dvlp, foll..."
97,10,22,ecom.space,We are coming up with the Best 21 Books that w...,182,#books #book #motivation #inspiration #life#bo...,3 hours,10,[booksbookmotivationinspirationlifebookloverli...,"[We, are, coming, up, with, the, Best, 21, Boo..."
98,11,24,lb3enterprises,We’re only paid to move dirt once. It’s not ju...,2039,#heavyequipment #underconstruction#dozer #real...,3 hours,222,[heavyequipmentunderconstructiondozerrealestat...,"[Were, only, paid, to, move, dirt, once, Its, ..."
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]"

In [27]:
df["string_feature"] = df.apply(lambda x: x["Caption_splited"] + x["Hashtags_splited"] , axis=1) 
df["string_feature"]

0     [Who, are, DataScientist, and, what, do, they,...
1     [We, all, know, where, its, going, We, just, h...
2     [Alexander, Barinov, 4, years, as, CFO, in, mu...
3     [sfad, iotcreworkplaceCDObigdatatechnologytech...
4     [Ever, missed, a, call, while, your, phone, wa...
                            ...
95    [328, S, Wetherly, Drive, Beverly, Hills, CA, ...
96    [CredittristankappelTo, find, more, dvlp, foll...
97    [We, are, coming, up, with, the, Best, 21, Boo...
98    [Were, only, paid, to, move, dirt, once, Its, ...
99    [Obtén, tu, tienda, en, línea, ahora, marketin...
Name: string_feature, Length: 100, dtype: object

In [28]:
df = df.explode('string_feature')

In [29]:
df

,Unnamed: 0,S.No,USERNAME,Caption,Followers,Hashtags,Time since posted,Likes,Hashtags_splited,Caption_splited,string_feature
0,0,1,mikequindazzi,Who are #DataScientist and what do they do? >>...,1600,#MachineLearning #AI #DataAnalytics #DataScien...,11 hours,139,"[MachineLearning, AI, DataAnalytics, DataScien...","[Who, are, DataScientist, and, what, do, they,...",Who
0,0,1,mikequindazzi,Who are #DataScientist and what do they do? >>...,1600,#MachineLearning #AI #DataAnalytics #DataScien...,11 hours,139,"[MachineLearning, AI, DataAnalytics, DataScien...","[Who, are, DataScientist, and, what, do, they,...",are
0,0,1,mikequindazzi,Who are #DataScientist and what do they do? >>...,1600,#MachineLearning #AI #DataAnalytics #DataScien...,11 hours,139,"[MachineLearning, AI, DataAnalytics, DataScien...","[Who, are, DataScientist, and, what, do, they,...",DataScientist
0,0,1,mikequindazzi,Who are #DataScientist and what do they do? >>...,1600,#MachineLearning #AI #DataAnalytics #DataScien...,11 hours,139,"[MachineLearning, AI, DataAnalytics, DataScien...","[Who, are, DataScientist, and, what, do, they,...",and
0,0,1,mikequindazzi,Who are #DataScientist and what do they do? >>...,1600,#MachineLearning #AI #DataAnalytics #DataScien...,11 hours,139,"[MachineLearning, AI, DataAnalytics, DataScien...","[Who, are, DataScientist, and, what, do, they,...",what
...,...,...,...,...,...,...,...,...,...,...,...
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",en
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",línea
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",ahora
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",marketingprogrammingdevelopmentdesarrollowebde...
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",argentinachileuruguaydigitalmarketingsocialmed...

In [31]:
df[["Followers", "Likes", "string_feature"]]

    Followers  Likes                                     string_feature
0        1600    139                                                Who
0        1600    139                                                are
0        1600    139                                      DataScientist
0        1600    139                                                and
0        1600    139                                               what
..        ...    ...                                                ...
99        741    109                                                 en
99        741    109                                              línea
99        741    109                                              ahora
99        741    109  marketingprogrammingdevelopmentdesarrollowebde...
99        741    109  argentinachileuruguaydigitalmarketingsocialmed...

[2390 rows x 3 columns]

In [32]:
df.loc[99]

,Unnamed: 0,S.No,USERNAME,Caption,Followers,Hashtags,Time since posted,Likes,Hashtags_splited,Caption_splited,string_feature
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",Obtén
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",tu
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",tienda
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",en
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",línea
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",ahora
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",marketingprogrammingdevelopmentdesarrollowebde...
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109,[marketingprogrammingdevelopmentdesarrollowebd...,"[Obtén, tu, tienda, en, línea, ahora]",argentinachileuruguaydigitalmarketingsocialmed...

error: nothing to repeat at position 0